name: Verify User Bundle Prototype CI
on: [push, pull_request]
jobs:
  verifier:
    name: ResetPassword
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

#      - name: Validate composer .json and .lock
#        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check src with php-cs-Fixer
          run: vendor/bin/php-cs-fixer fix --config $GITHUB_WORKSPACE/.php_cs.dist --diff --diff-format udiff --dry-run

      - name: Psalm Static Analysis
        run: vendor/bin/psalm -c psalm.xml

      - name: Unit Tests
        run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist
        if: always()
